package vsu.cs.tasks;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.*;
import java.awt.event.*;
import java.util.Random;

import static java.lang.Math.cos;
import static java.lang.Math.sin;


public class MyJFrame extends javax.swing.JFrame {
    private DrawPanel drawPanel;
    private Polygon poly;
    private double ygel;
    private static int x1 = 500;
    private static int y1 = 100;
    private int R = 50;
    private int dx = 0;
    private int dy = 0;
    private int N = 3;
    //Компонент для рисования


    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
        //Создаем панель рисования
        drawPanel = new DrawPanel();
        //Устанавливаем панель рисования на панель
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(drawPanel, BorderLayout.CENTER);
        jPanel1.addMouseMotionListener(new MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                jPanel1MouseDragged(e);
            }

            @Override
            public void mouseMoved(MouseEvent e) {

            }
        });
        jPanel1.addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                jPanel1MouseWheelMoved( e);
            }
        });
        drawPanel.addDrawListener(new IDrawListener() {
            @Override
            public void DrawEvent(DrawEventArg evt) {
                DrawEventPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 237, Short.MAX_VALUE)
        );

        jButton1.setText("+1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton3.setText("++");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton4.setText("++");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                                 .addComponent(jButton1)
                                .addComponent(jButton2)
                                .addGap(160, 160, 160)
                                .addComponent(jButton3)
                                .addGap(160, 160, 160)
                                .addComponent(jButton4)
                                .addContainerGap(161, Short.MAX_VALUE))


        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                               .addComponent(jButton2)
                                .addComponent(jButton3)
                                .addComponent(jButton4)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        N++;
        drawPanel.repaint();

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if ( N>=3 ){
            N--;
            drawPanel.repaint();
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        R+=10;
        drawPanel.repaint();
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        R-=10;
        drawPanel.repaint();
    }
    public void jPanel1MousePressed(MouseEvent e) {
        dx = e.getX();
        dy = e.getY();
    }

    public void jPanel1MouseRealised(MouseEvent e) {
    }

    public void jPanel1MouseWheelMoved(MouseEvent e) {
        ygel+=0.15;
        drawPanel.repaint();
    }

    public void jPanel1MouseDragged(MouseEvent e) {
        x1 = e.getX();
        y1 = e.getY();
        drawPanel.repaint();
    }

    private void DrawEventPerformed (DrawEventArg evt) {
        //Запоминается графический интерфейс
        Graphics g = evt.getGraphics();

        int[] x = new int[N];
        int[] y = new int[N];

        double angle;
        for (int i = 0; i < N; i++) {
            angle = 2 * Math.PI * i / N + ygel;
            x[i] = (int) (R * cos(angle) +x1);
            y[i] = (int) (R * sin(angle) +y1);
        }
        poly = new Polygon(x, y, x.length);
        g.setColor(Color.BLUE);
        g.fillPolygon(poly);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
